### ISSUE TITLE
Remove .eslintrc from npm package

### ISSUE THREAD

**Issue by dy** [ljharb/is-negative-zero#4]
If I run eslint from a dependent package, that raises

```sh
$ eslint .
Error: Cannot find module '@ljharb/eslint-config'
Referenced from: C:\projects\gl-waveform\demo\node_modules\is-negative-zero\.eslintrc
```

**Comment by ljharb** [comment]
are you eslinting node_modules? Those are ignored by default; you should only be linting your own code.

**Comment by dy** [comment]
I do “eslint .”, and it scans folder ignored by .gitignore and everything within.

**Comment by ljharb** [comment]
It shouldn’t - by default eslint respects gitignore. This may be an issue with your eslint configuration.

**Comment by ljharb** [comment]
You may need an .eslintignore file with `node_modules/` in it.

**Comment by dy** [comment]
Just curious what is the purpose of distributing custom eslint config with the package? It does not seem normal forcing every consumer to add .eslintignore

**Comment by ljharb** [comment]
Again, the default for everyone else is to not lint node_modules.

Even if i took extra steps and filtered that file, your linting rules might warn on my code. What would you do then? I’m not going to conform this repo to your coding style.

The proper thing to do here is what every other eslint user on the planet does - only lint your own code, and never anything in node_modules.

**Comment by dy** [comment]
The folder structure is
```
- demo
-- node_modules
- node_modules
- .gitignore
```
`.gitignore` includes `demo` folder, but eslint still parses nested `node_modules`, but not the root one. Seems like some of the related issues https://github.com/facebook/create-react-app/issues/4246.

Sorry it did not work. Switching to the other package for now.

**Comment by ljharb** [comment]
In that case, your nonstandard folder structure means you need an eslintignore file that excludes nested node_modules folders. Without that, you’ll have tons of problems no matter what modules you use.
